name: CI

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: "**"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Verify build
        run: go build ./...

      - name: Go vet
        run: go vet ./...
      
      - name: Check Go version
        run: go version

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.2
          args: --timeout=5m

  acceptance:
    needs: build-and-lint
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      TF_ACC: "1"
      SOTOON_API_TOKEN:    ${{ secrets.SOTOON_API_TOKEN }}
      SOTOON_WORKSPACE_ID: ${{ secrets.SOTOON_WORKSPACE_ID }}
      SOTOON_USER_ID:      ${{ secrets.SOTOON_USER_ID }}
      SOTOON_API_HOST:     ${{ secrets.SOTOON_API_HOST }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
      - name: Acceptance tests
        if: env.SOTOON_API_TOKEN != ''
        run: |
          go test ./internal/provider -tags=acceptance -v -run '^TestAcc' -count=1 -timeout 60m -parallel 1
