name: CI

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: "**"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Verify build
        run: go build ./...

      - name: Go vet
        run: go vet ./...
      
      - name: Check Go version
        run: go version

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.2
          args: --timeout=5m

  test:
    needs: build-and-lint
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
      - name: unit tests
        run: |
          go test ./internal/... -tags=unit -v -run '^TestUnit' -count=1 -timeout 60m -parallel 1
